### ISSUE TITLE
Opening a .deb file directly launches the app but doesn't show the file opened

### ISSUE THREAD

**Issue by ChildishGiant** [donadigo/eddy#110]

**Comment by tonywei92** [comment]
I wonder if this is a Elementary OS 6 problem or Eddy problem

**Comment by RDKRACZ** [comment]
Eddy's as I have this problem on Ubuntu too.

**Comment by tonywei92** [comment]
Tried to install Eddy from the `README.md` instruction, it's working flawlessly now. Highly chance is ElementaryOS 6 problem

**Comment by WebShapedBiz** [comment]
On my Odin, the old version 1.3.0, .deb file downloaded from the Hera repo, works just fine. The Flatpak version however runs fine but it doesn't link to the file when opening by clicking the .deb file, it has to be selected manually.
