### ISSUE TITLE
Show progress in detail view

### ISSUE THREAD

**Issue by eliocamp** [donadigo/eddy#12]
It would be great to  see the actual progress of the installation (the same text as shown during installation in the terminal) when clicking on the package being installed. Right now it only shows details of the package (which is awesome).

**Comment by donadigo** [comment]
At some point, in the next release I want to implement a progress bar into the app icon you see in the dock. This way you could always see the progress of installation even if you don't see the window. Then I think the progress isn't needed in the details view anymore. What do you think?

**Comment by eliocamp** [comment]
Yes, that's good,

**Comment by donadigo** [comment]
Fixed in https://github.com/donadigo/eddy/commit/eb3f2adac6c77d6e708f6db766af51592c8d65a7, will be available in 1.0.4.
