### ISSUE TITLE
[Feature Request]: Sort Packages by Installed/Not Installed 

### ISSUE THREAD

**Issue by rhoconlinux** [donadigo/eddy#13]
Hi there, first of all, great work.

It would be nice to be able to sort the packages in downloads directory. Specially to give priority to those not installed yet. 

Hope that this feature can be implemented in the future!

Cheers

**Comment by donadigo** [comment]
Thanks for reporting that! I totally forgot about sorting these. Fixed in https://github.com/donadigo/eddy/commit/04664c1ba39792bd7f5180e938e1c16e216b905c and will be a part of 1.0.4.
