### ISSUE TITLE
Eddy not installing deb packages

### ISSUE THREAD

**Issue by aindriu80** [donadigo/eddy#131]
I'm running Ubuntu 21.04 and I can't get Eddy to install a deb package.  I've followed the installation instructions on this Git repo but I've had no luck.  When I load up Eddy and click install it just says finished instantly and doesn't install the deb package.  I tried to debug with

`G_MESSAGES_DEBUG=all com.github.donadigo.eddy --debug`

which outputs the following...

```
G_MESSAGES_DEBUG=all com.github.donadigo.eddy --debug                                                       1 ✘  at 20:49:14   ▓▒░
(process:69873): GLib-GIO-DEBUG: 20:49:34.093: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ?gsettings-backend?
(process:69873): dconf-DEBUG: 20:49:34.093: watch_fast: "/com/github/donadigo/eddy/" (establishing: 0, active: 0)
** (process:69873): DEBUG: 20:49:34.094: Settings.vala:150: Loading settings from schema 'com.github.donadigo.eddy'
(process:69873): dconf-DEBUG: 20:49:34.094: change_fast
** (process:69873): DEBUG: 20:49:34.094: Application.vala:35: Using cached mime types from com.github.donadigo.eddy schema: application/vnd.debian.binary-package; application/x-deb
Rogha anaithnid --debug
(com.github.donadigo.eddy:69873): dconf-DEBUG: 20:49:34.094: sync
(com.github.donadigo.eddy:69873): dconf-DEBUG: 20:49:34.095: watch_established: "/com/github/donadigo/eddy/" (establishing: 1)



```
Below you can see a screenshot of what happens - it says installed but it isn't installed.... how do I fix this?

![2022-06-05_20-53](https://user-images.githubusercontent.com/8885837/172068129-91054e18-eb42-4566-a729-ad01215e7564.png)

**Comment by sandenbergmelo** [comment]
I'm running Ubuntu 22.04 and I have the same problem.

**Comment by JonathanLochridge** [comment]
I am having a similar issue with different software on Pop! OS 22.04, But, It just gives me error code 100 whenever I try to install any debian package. I tried it with a good 10 or so different ones. No idea why but it is getting a bit annoying. I even tried just trying to install a an appimage based app installer.So, I could get arround this not working. But, I couldn't find one I could manage to install without it simply being a .deb file I couldn't install since this doesn't work.
![eddyError](https://user-images.githubusercontent.com/43937225/174466612-94388a6e-2ba2-4a88-a4d0-30f067790787.png)
.

**Comment by blyxyas** [comment]
The same issue as Jonathan. While trying to downgrade VSCode

**Comment by Kitato** [comment]
> I am having a similar issue with different software on Pop! OS 22.04, But, It just gives me error code 100 whenever I try to install any debian package. I tried it with a good 10 or so different ones. No idea why but it is getting a bit annoying. I even tried just trying to install a an appimage based app installer.So, I could get arround this not working. But, I couldn't find one I could manage to install without it simply being a .deb file I couldn't install since this doesn't work. ![eddyError](https://user-images.githubusercontent.com/43937225/174466612-94388a6e-2ba2-4a88-a4d0-30f067790787.png) .

exactly the same here. is there any solution to this ?

**Comment by j2l** [comment]
After grinding my teeth for month about this one, 
I thought of a "Debian vs Ubuntu fight" but actually no.

I replaced Eddy with gdebi and deb packages now install. 
`apt install gdebi`

Hope it helps you too.

**Comment by MH0386** [comment]
> After grinding my teeth for months about this one, 
> I thought of a "Debian vs Ubuntu fight" but actually no.
> 
> I replaced Eddy with gdebi and deb packages now install. 
> `apt install gdebi`
> 
> Hope it helps you too.
> Goodbye dishwasher's error codes!
> 
> Because "code 100" without even giving a hint about the error or a link to a manual to decrypt what error 100 stands for is just ... 
> 

Unfortunately, it doesn't work for me either.

**Comment by donadigo** [comment]
The update fixing this is now available in AppCenter.
