### ISSUE TITLE
Eddy and New Elementary OS 7

### ISSUE THREAD

**Issue by YaroslavChepel** [donadigo/eddy#134]
I have installed a new Elementary OS 7 and wanted to install eddy. While doing this I ran into a problem, eddy didn't install I App enter and from Terminal, and when I tried to make a build of eddy from github I got some errors, but the application ran(yes it worked, but didn't install deb files). I hope you will re-do the GTK4 app for the new elementary OS 7, or send a ready-made flat pack.

**Comment by Pvch3r3t3** [comment]
When a new version for elementaryOS 7? Please....

**Comment by YaroslavChepel** [comment]
Here it is, lol
https://elementary.io/en/

**Comment by MH0386** [comment]
I have the same problem. It doesn't install anything when I click the install button.

**Comment by donadigo** [comment]
Hey, this problem is now fixed in master and will be released to elementary OS 7 soon.

**Comment by YaroslavChepel** [comment]
> Hey, this problem is now fixed in master and will be released to elementary OS 7 soon.

Thanks a lot :D

**Comment by donadigo** [comment]
The update fixing this is now available in AppCenter.
