### ISSUE TITLE
No option to update installed deb-packages

### ISSUE THREAD

**Issue by darim92** [donadigo/eddy#14]
There is no option to update installed packages.

For example: I've atom-editor v1.16 installed on my machine and I want to install v1.17 from the website. 
If I open the atom.deb with eddy the only option I get is to uninstall atom-editor. 
Gdebi would update or overwrite the installed package with the new version.

**Comment by donadigo** [comment]
Fixed in https://github.com/donadigo/eddy/commit/f325be206d38fe2f49b6b472ec58c91f2104ba02, and available in the newest 1.1.4 update.
