### ISSUE TITLE
Window resize to fit package description but could be too big

### ISSUE THREAD

**Issue by megatux** [donadigo/eddy#17]
e.g. this package with a very looong name. The app window resize more wider than my desktop
![e.g. this package with a very looong name](https://cloud.githubusercontent.com/assets/850020/26517663/02e68510-4274-11e7-90a8-976afe721c36.png)
I think the window should be clever on resizing and also that description text should be splitted on several lines (soft wrap).

**Comment by donadigo** [comment]
Fixed in https://github.com/donadigo/eddy/commit/5427fd8989542b1b76e58a03506dbd2803dca959. Thanks for reporting the issue. The fix will be available in 1.0.5.
