### ISSUE TITLE
Does not close with Ctrl-Q | Ctrol-W

### ISSUE THREAD

**Issue by megatux** [donadigo/eddy#18]
Or meta-Q, or Escape, etc. I don't know if the keys are part of the ElementaryOS UX guidelines, but I'm used to close apps with keyboard. Gnome has these behavior in its guidelines.

**Comment by megatux** [comment]
Made a PR #19 for this.

**Comment by donadigo** [comment]
Fixed in https://github.com/donadigo/eddy/commit/1a8ae990d6e9da393593d691ac033d2d11742c3f, thanks!
