### ISSUE TITLE
The "Suggest Translation" button is pointing to the wrong link

### ISSUE THREAD

**Issue by GabrielMGitHub** [donadigo/eddy#20]
The "Suggest Translation" button is pointing to the wrong link. 
https://github.com/donadigo/eddy
![captura de tela de 2017-05-27 16-35-58](https://cloud.githubusercontent.com/assets/8754997/26523937/9a9dc1bc-42fa-11e7-8937-d50bc6927dd9.png)

**Comment by donadigo** [comment]
There is currently no translation setup / service for Eddy, and I don't know if there will ever be. I'll see if the button can be removed from the dialog though, closing.

**Comment by GabrielMGitHub** [comment]
@donadigo
I think it's wrong not to have the translation for other languages, and the withdrawal of the dialogue, because I believe it does not match the rules of the elementary store.
