### ISSUE TITLE
Progress bars not synced correctly

### ISSUE THREAD

**Issue by jwinnie** [donadigo/eddy#21]
While using Eddy in elementaryOS 0.4.1, I noticed that the progress bar in the dock and the progress bar in the window did not show the same progress. This was kind of confusing because I didn't know which progress bar was right.

**Comment by donadigo** [comment]
Did you install more than one package? If you start install more than one, the progress bar on the icon will show the overall progress of the installation, not for one package. Perhaps this should be changed, but I think the user expects the progress bar to show the entire progress and the app window shows the progress for each package. Are you able to tell me more information about the issue?

**Comment by jwinnie** [comment]
This issue still happens with one package. One progress bar is updated before the other.

**Comment by donadigo** [comment]
@jwinnie could you tell / link me to the package you're installing? This could help the resolving the issue much more quickly.

**Comment by jepotter1-archive** [comment]
Here is a video:

https://youtu.be/BswPwFVh9wg

**Comment by jwinnie** [comment]
Stale
