### ISSUE TITLE
Show if Download folder is empty.

### ISSUE THREAD

**Issue by harisvsulaiman** [donadigo/eddy#25]
Presently the progress spinner is shown indefinitely when the downloads folder is empty.
Shouldn't it show some kind of alert to show that the download directory is empty?
**Screenshots attached below.**
![image](https://cloud.githubusercontent.com/assets/6212932/26749417/cc0e36f0-4827-11e7-9e69-ddafe815311e.png)

**Comment by donadigo** [comment]
This has been fixed recently in master. The "open from Downloads" button will not appear when there is no packages to install from it.
