### ISSUE TITLE
Not enough contrast on the window title

### ISSUE THREAD

**Issue by jwinnie** [donadigo/eddy#31]
The background on the window title is red while the text is black, so the text becomes hard to see. The text could be changed to white or the background changed to a lighter color.

**Comment by aggalex** [comment]
I was about to say this. Reading the title or trying to find the app window icons is a real strain to the eye. [Harvey](https://appcenter.elementary.io/com.github.danrabbit.harvey.desktop) can help you find good contrasting colors. It's an application developed by by Daniel Forèe, and as he says, "It's the God everyone needs". ;-
![screenshot from 2017-07-10 15 35 50](https://user-images.githubusercontent.com/11951328/28018612-aa530744-6586-11e7-9735-f8aff501d991.png)
)

**Comment by donadigo** [comment]
Is this looking okay to you?
![screenshot](http://i.imgur.com/Hsiyasa.png)

**Comment by donadigo** [comment]
Fixed in https://github.com/donadigo/eddy/commit/c886e0ea76a143b3db4878dca3a209702724a0b4.
