### ISSUE TITLE
I can't see Eddy on Appcenter..

### ISSUE THREAD

**Issue by turkerpektas** [donadigo/eddy#32]
Hi! I can't install Eddy from Appcenter. It's sayin' not found. Which PPA's I should look? Thanks..

**Comment by donadigo** [comment]
Can you tell me what your OS is? I assume it's elementary OS Loki? There might be some issues on the Houston's server side, but I can do nothing about this issue in this project.

**Comment by turkerpektas** [comment]
Yes, I'm using Elementary OS Loki. I changed some settings for installing WPS Office and now, I can see only some softwares which ones avilable for Ubuntu..

**Comment by donadigo** [comment]
What happens if you go to the main page (that is https://github.com/donadigo/eddy), and click "Get it on AppCenter"?

**Comment by turkerpektas** [comment]
![2017-07-09 18 08 12 den ekran goruntusu](https://user-images.githubusercontent.com/29827598/27995177-bbc6b976-64d2-11e7-90f4-ff447c099e29.png)
Here is my screenshot..

**Comment by turkerpektas** [comment]
Can I install app from github?

**Comment by donadigo** [comment]
Hm, It looks like you've removed the main AppCenter's PPA. Yes, you can "install" it, but you would have to compile it. I've described the process in the README.

**Comment by turkerpektas** [comment]
Do you know AppCenter's PPA?

**Comment by turkerpektas** [comment]
I think the problem was temporary. I changed my server to US and problem solved. Thanks for help..

**Comment by hachene** [comment]
Hey, ghost, It seems like this is happening again. I just installed the brand new Elementary OS 6 and I cannot find your awesome app : )

**Comment by donadigo** [comment]
Eddy and AppEditor are not yet available for elementary OS 6. They should be soon though.

**Comment by hachene** [comment]
> Eddy and AppEditor are not yet available for elementary OS 6. They should be soon though.

Oh, ok! Looking forward to it. Thanks for the update!
