### ISSUE TITLE
Header styles affect open file dialog

### ISSUE THREAD

**Issue by btkostner** [donadigo/eddy#37]
The red and white header style seems to be affecting the open file dialog as well:

![screenshot from 2017-08-24 10 58 32](https://user-images.githubusercontent.com/3385679/29681002-3da31af0-88bb-11e7-8e2f-6e3181f9aac0.png)

Running elementary 0.4.1 Loki stable (mostly)

**Comment by donadigo** [comment]
At this point, this is blocked since this is a stylesheet issue, I'm not gonna close it, but I will when this issue gets fixed there.

**Comment by unc926** [comment]
need some  ui fix
change open file icon » symbolic style
centered progress bar & add progressbar background.

example: 

![screenshot_1](https://user-images.githubusercontent.com/30185386/31499116-893aef24-af6c-11e7-8be6-07f22a4ba48c.png)

**Comment by donadigo** [comment]
I don't think this is the case anymore. We even stopped using a hack to make this dialog look decent in 6.0. Closing.
