### ISSUE TITLE
Adding translations not working

### ISSUE THREAD

**Issue by pefferen** [donadigo/eddy#38]
see #22 , I tried adding translated strings to nl.po, I see changes in the file at `/usr/local/share/locale-langpack/nl/LC_MESSAGES/com.github.donadigo.eddy.mo` . When running the application i do not see the translated strings. I could be doing it wrong.

**Comment by donadigo** [comment]
Do you have the translated language set as your main system language? I just merged https://github.com/donadigo/eddy/pull/39 and after setting the system language to German, all the strings were visible to me.

**Comment by pefferen** [comment]
Maybe there is something wrong with my setup. I executed the steps from the readme. in #40 I added the po file withe the Dutch translations.

**Comment by donadigo** [comment]
I'm going to close this for now, if you have any problems still, please reopen.
