### ISSUE TITLE
Installed Apps Log

### ISSUE THREAD

**Issue by winuxue** [donadigo/eddy#49]
when you install apps, you have the uninstall button at the rigth, but when you close the window, you don't have how to uninstall the application.
Maybe would be a good idea have a log of previously installed apps, this way we can uninstall apps at any time

**Comment by donadigo** [comment]
Fixed in https://github.com/donadigo/eddy/commit/f70d5ccecf4c99f95ba0d65b8c3e4829e4b895e5. Closing.
