### ISSUE TITLE
The source directory "/home/username" does not appear to contain CMakeLists.txt. 

### ISSUE THREAD

**Issue by NaiCity** [donadigo/eddy#50]
Hello there, I've been trying to run cmake -DCMAKE_INSTALL_PREFIX=/usr .. atfer creating a build directory and navigating to it but I'm getting the above error. Where could I be going wrong ?

**Comment by donadigo** [comment]
Hello! After you clone a repository, which I assume you've already done, you need to enter the root of the Eddy's source code:
`cd eddy` and then execute all the following commands like `cmake ..`.

**Comment by NaiCity** [comment]
I'm getting this in the output

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
CMake Error at CMakeLists.txt:10 (add_executable):
  Cannot find source file:

    eeprom_fix.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error at CMakeLists.txt:10 (add_executable):
  Cannot find source file:

    fwinfo.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error at CMakeLists.txt:10 (add_executable):
  Cannot find source file:

    miniboot.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error at CMakeLists.txt:10 (add_executable):
  Cannot find source file:

    checksum.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: eeprom_fix
CMake Error: Cannot determine link language for target "eeprom_fix".
CMake Error: CMake can not determine linker language for target: fwinfo
CMake Error: Cannot determine link language for target "fwinfo".
CMake Error: CMake can not determine linker language for target: miniboot
CMake Error: Cannot determine link language for target "miniboot".
CMake Error: CMake can not determine linker language for target: checksum
CMake Error: Cannot determine link language for target "checksum".
-- Generating done
-- Build files have been written to: /home/jamie/eddy
root@jamie-VirtualBox:/home/jamie/eddy# make
Scanning dependencies of target eeprom_fix
make[2]: *** No rule to make target 'CMakeFiles/eeprom_fix.dir/build'.  Stop.
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/eeprom_fix.dir/all' failed
make[1]: *** [CMakeFiles/eeprom_fix.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by NaiCity** [comment]
I have tried doing that, but to no avail. I cloned the project, navigated
to Eddy using cd  eddy and run the cmake command but still ended up with
the error.

 Another question,  at what point do you create the build directory  and
navigate  to it so as to run the cmake command ? I'm confused.

**Comment by donadigo** [comment]
What distro are you using? Creating the build directory happens after cd'ing to eddy source folder.

**Comment by NaiCity** [comment]
Hey,  I've managed cding into the src folder inside eddy directory  and
executing  the command 😊.
 From  there, how do I proceed?
I'm using Elementary  OS 0.4.1 7 Loki

**Comment by donadigo** [comment]
Just follow the next instructions:
Execute `sudo make install` and that should compile and install Eddy to your system.
Also curious: why do you want to compile Eddy from source?

**Comment by NaiCity** [comment]
I was just curious to learn about compiling it from source code.
 So will I create a build  folder inside the src directory  then cd into it
and run the cmake command again?

**Comment by donadigo** [comment]
No, all you need to do is:
`git clone https://github.com/donadigo/eddy.git`
`cd eddy`
`mkdir build && cd build`
`cmake .. -DCMAKE_INSTALL_PREFIX=/usr`
`sudo make install`

That's it.

**Comment by NaiCity** [comment]
Thank you  so much  for that  clarification.  I'll try afresh  and give you
feedback.

**Comment by NaiCity** [comment]
Thank you. All commands work now. I also noticed you can download it
straight from app center.

**Comment by NaiCity** [comment]
Final question, does installation from source have the same result as
installing from the app center ?

**Comment by donadigo** [comment]
Installing from AppCenter is the preferred way since it contains the stable, tested version of the application. Compiling from source provides you with the latest "commit" with the newest functionality that may not be released as a part of an update in AppCenter or in general. Essentially source mostly is not what is in the AppCenter.

**Comment by suunee** [comment]
> No, all you need to do is:
> `git clone https://github.com/donadigo/eddy.git`
> `cd eddy`
> `mkdir build && cd build`
> `cmake .. -DCMAKE_INSTALL_PREFIX=/usr`
> `sudo make install`
> 
> That's it.

Hello, i followed exactly those steps but i keep having this error... im using ZorinOS Core, any help?
"CMake Error: The source directory "/home/leansune" does not appear to contain CMakeLists.txt."
