### ISSUE TITLE
App Payment

### ISSUE THREAD

**Issue by ghost** [donadigo/eddy#52]
Hey,

I couldn't find a way to contact you. 

You should really suggest a $1 or more donation for Eddy. Everytime I install it, I think, "I wish I could donate to this project."

email me at h4ck3r9@riseup.net

Also, @h4ck3r9 on [Mastodon](https://mastodon.rocks/web/accounts/21347)

**Comment by donadigo** [comment]
Thank you so much for your support! Unfortunately Stripe is not available in my country and so I cannot monetize anything. I'm also not yet of age (I'm currently 17) and it's kind of hard to setup anything for donations or payments. Maybe in the future...

**Comment by h4ck3r9** [comment]
Ah, well that would be difficult I guess. Well, I love the app! I'll just give you encouragement until there is another way to say thank you! :)

**Comment by donadigo** [comment]
Closing as the app has been monetized.
