### ISSUE TITLE
Doesn't work on Elementary Juno beta1

### ISSUE THREAD

**Issue by opnay** [donadigo/eddy#59]
![2018-07-04 20-58-35](https://user-images.githubusercontent.com/1689721/42275999-098f7844-7fcd-11e8-9997-02357f8bab63.png)

Today(2018.07.04/Korea), Released Elementary OS Juno beta1.
and I installed it and eddy, but not opened this app.

so, i use terminal with
```
com.github.donadigo.eddy
```
that will show `Settings schema 'com.github.donadigo.eddy' is not installed`.

I think you must update debian package installation script.

p.s // sorry my bad english.

**Comment by donadigo** [comment]
Oops, caused by the meson port... I'm releasing 1.2.1 soon with the fix so it should be available soon in AppCenter as an update. Thank you for your detailed report!

**Comment by donadigo** [comment]
Released 1.2.1 with the fix. Should be available in a couple of minutes / hours.
