### ISSUE TITLE
"Unable to open files or uris with this app" when clicking on a .deb

### ISSUE THREAD

**Issue by cassidyjames** [donadigo/eddy#7]
When I click on a .deb from Files and try to open it with Eddy, I get an error dialog that says "Unable to open files or uris with this app"

- Eddy 1.0
- elementary OS Loki (daily)

**Comment by donadigo** [comment]
Fixed in https://github.com/donadigo/eddy/commit/11a5708a8df2dba186900a31dc6d1a7cdea3cbed.
