### ISSUE TITLE
How can I install it on other debian based distros?

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [donadigo/eddy#72]
Dear Dev,

I was wondering how can I install this app on my other debian based distro,
The only way I can think of is installing appcenter to those distros.
Can you create an Appimage or .deb file for it?

Sorry if you have already created one ,I was not able to find one.

**Comment by donadigo** [comment]
For some reason 4 newest releases don't contain the built .deb file, but you can download a .deb right now that was built by AppCenter for v1.1.7: https://github.com/donadigo/eddy/releases/download/1.1.7/com.github.donadigo.eddy_1.1.7_amd64.deb

I'll see if I can build the .deb for the newest version manually.

**Comment by Ashutosh-Kukreti** [comment]
Thank you
