### ISSUE TITLE
Can't uninstall installed apps

### ISSUE THREAD

**Issue by jordan080** [donadigo/eddy#77]
There's not an option to uninstall installed apps with Eddy. Since they don't appear at AppCenter, the only way is to use the terminal, and this can be a little scary to new users.

**Comment by donadigo** [comment]
I do agree that there could be a simpler way to view previously installed apps so one can uninstall them, it is not quite intuitive to drag the original deb file back to the app only to uninstall it, will think about it and thanks for the report!

**Comment by donadigo** [comment]
We now have an option to view previously installed packages. Closing.
