### ISSUE TITLE
About dialog is translucent

### ISSUE THREAD

**Issue by cassidyjames** [donadigo/eddy#8]
Might actually be a GTK stylesheet issue with theme color or something, but I'm seeing it in Eddy.

![screenshot from 2017-04-22 14 05 07](https://cloud.githubusercontent.com/assets/611168/25307804/eaac22b8-2764-11e7-8db6-cde1d78468bb.png)

**Comment by donadigo** [comment]
Nothing I can do here since this is an issue with what version of Granite Houston uses to build .deb files.
