### ISSUE TITLE
Purchasing Eddy

### ISSUE THREAD

**Issue by djstringy** [donadigo/eddy#84]
Why do I have to pay for eddy every time I reinstall the elementary OS

**Comment by donadigo** [comment]
You don't need to! I think this is something that the elementary OS team is working on which is remembering all the purchases in an account service. If you've already paid or don't want to pay, enter 0$ to download for free. Nothing I can do from the app side of things so closing.

**Comment by djstringy** [comment]
Well i had to jut reinstall my elementary box because of freezing issues and I had to repay for it. They need to add an account to the OS so it will remember what we paid for and such
