### ISSUE TITLE
Unable to install after purchase

### ISSUE THREAD

**Issue by pnyneil** [donadigo/eddy#85]
I paid $1 and clicked on install then nothing happened. Please help. I already paid $5 to install it on other laptop but when I encountered a software problem in general, I had to do clean install on elementary os but I realized doing that I'd have to redownload apps that i lost during clean install. I don't want to keep paying when I already paid. Thank you in advance.

**Comment by donadigo** [comment]
Hello, sorry for the late response. Unfortunately, the issue seems to be on the AppCenter side and not something with Eddy. If you've already paid, you can always enter $0 in the price field to download for free, as such, I'm closing this issue.
