### ISSUE TITLE
I PAID 5 DOLLARS AND IT DID NOT DOWNLOAD ANYTHING.

### ISSUE THREAD

**Issue by MrNobody3417** [donadigo/eddy#87]
Good morning I purchased the application from the store. But he didn't download anything, he asks me to pay again. It does not seem right.

I wish the application was given to me.

**Comment by donadigo** [comment]
Hello! If AppCenter didn't download anything, try again but enter $0 in the price field to not pay. Unfortunately nothing I can do from my side here to help you.
