### ISSUE TITLE
Cannot build, 'Could NOT find Vala (missing: VALA_EXECUTABLE)'

### ISSUE THREAD

**Issue by yerbestpal** [donadigo/eddy#9]
During the build process I cannot pass `make ..`. I get the following:
```
ross@thinky:~/eddy/build$ cmake ..
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Vala (missing: VALA_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindVala.cmake:55 (find_package_handle_standard_args)
  src/CMakeLists.txt:1 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/ross/eddy/build/CMakeFiles/CMakeOutput.log"
```

Unfortunately I can't make much sense of that log.

**Comment by donadigo** [comment]
Oups, sorry. I forgot to include `valac` in the README as a dependency. It is now present in the latest commit. You can fix this issue now by installing valac: `sudo apt install valac` and re-building the app from scratch (remove previous build files).

**Comment by yerbestpal** [comment]
Brilliant, that worked a treat. Thanks. Classy app btw, well done.
